#!/usr/bin/env bash
# Infinite loop printing message and traps SIGTERM to print special message

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
