#!/usr/bin/env bash
# A script that prints a message in an infinite loop and handles SIGTERM gracefully

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
