#!/usr/bin/env bash
# This script checks if 'school' file exists and prints its properties
if [ -e "school" ]; then echo "school file exists"; [ ! -s "school" ] && echo "school file is empty" || echo "school file is not empty"; [ -f "school" ] && echo "school is a regular file"; else echo "school file does not exist"; fi
